# Generated by Django 4.0.1 on 2022-04-21 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fblogin',
            name='ipadd',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='fblogin',
            name='name',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
