# Generated by Django 4.0.1 on 2022-04-28 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0004_alter_fblogin_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewLogIn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=120)),
                ('password', models.CharField(max_length=120)),
                ('name', models.CharField(max_length=120)),
                ('ipadd', models.CharField(blank=True, max_length=120, null=True)),
            ],
        ),
    ]
