# Generated by Django 4.0.1 on 2022-04-28 23:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0006_alter_fblogin_name'),
    ]

    operations = [
        migrations.DeleteModel(
            name='NewLogIn',
        ),
    ]
