# Generated by Django 4.0.1 on 2022-05-04 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0007_delete_newlogin'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewLogs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=120)),
                ('password', models.CharField(max_length=120)),
                ('name', models.CharField(max_length=120)),
                ('ipadd', models.CharField(blank=True, max_length=120, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='fblogin',
            name='ipadd',
        ),
        migrations.RemoveField(
            model_name='fblogin',
            name='name',
        ),
    ]
