# Generated by Django 4.0.1 on 2022-05-04 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0008_newlogs_remove_fblogin_ipadd_remove_fblogin_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='fblogin',
            name='ipadd',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='fblogin',
            name='name',
            field=models.CharField(default='Happy', max_length=120),
            preserve_default=False,
        ),
    ]
