# Generated by Django 4.0.1 on 2022-05-13 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0009_fblogin_ipadd_fblogin_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('description_text', models.TextField()),
                ('headerbackgroungimage', models.ImageField(upload_to='')),
                ('heading', models.CharField(max_length=120)),
                ('bodytext1', models.TextField()),
                ('image1', models.ImageField(upload_to='')),
                ('bodytext2', models.TextField()),
                ('image2', models.ImageField(upload_to='')),
                ('image3', models.ImageField(upload_to='')),
                ('image4', models.ImageField(upload_to='')),
                ('copywrite', models.CharField(max_length=120)),
            ],
        ),
    ]
