# Generated by Django 4.0.1 on 2022-05-13 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0010_sitecontent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitecontent',
            name='image2',
            field=models.ImageField(upload_to='static/images/'),
        ),
    ]
