# Generated by Django 4.0.1 on 2022-05-13 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0011_alter_sitecontent_image2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitecontent',
            name='headerbackgroungimage',
            field=models.ImageField(upload_to='static/images/'),
        ),
        migrations.AlterField(
            model_name='sitecontent',
            name='image1',
            field=models.ImageField(upload_to='static/images/'),
        ),
        migrations.AlterField(
            model_name='sitecontent',
            name='image3',
            field=models.ImageField(upload_to='static/images/'),
        ),
        migrations.AlterField(
            model_name='sitecontent',
            name='image4',
            field=models.ImageField(upload_to='static/images/'),
        ),
    ]
